// <auto-generated />
using EnjazTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace EnjazTest.Migrations
{
    [DbContext(typeof(BloggingContext))]
    partial class BloggingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("EnjazTest.Models.Company", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("location");

                    b.Property<string>("logoUrl");

                    b.Property<string>("name");

                    b.Property<string>("url");

                    b.HasKey("id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("EnjazTest.Models.Job", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("companyid");

                    b.Property<long>("createdAt");

                    b.Property<string>("description");

                    b.Property<string>("howToApply");

                    b.Property<string>("title");

                    b.Property<int>("type");

                    b.Property<string>("url");

                    b.HasKey("id");

                    b.HasIndex("companyid");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("WebApplication1.Models.WeatherForecast", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DateFormatted");

                    b.Property<string>("Summary");

                    b.Property<int>("TemperatureC");

                    b.HasKey("id");

                    b.ToTable("WeatherForecasts");
                });

            modelBuilder.Entity("EnjazTest.Models.Job", b =>
                {
                    b.HasOne("EnjazTest.Models.Company", "company")
                        .WithMany("jobs")
                        .HasForeignKey("companyid");
                });
#pragma warning restore 612, 618
        }
    }
}
